### ISSUE TITLE
Yolov5 Segmentation on Jetson

### ISSUE THREAD

**Issue by NishaniKasineshan** [mailrocketsystems/JetsonYolov5#5]
@mailrocketsystems I need to implement yolov5 segmentation on jetson tx2. I followed your repo for yolov5 detection on jetson. For segmentation I think i need to create a script similar to YoloDet.py. Are you working on that or can you guide on how to implement yolov5 segmentation on jetson?

**Comment by captainvoldemort** [comment]
Hello, I have created a solution based on [This](https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5) repository. You can find the required code Here: https://github.com/yashreadytobox/JetsonYolov5 inside 'app_segmentation.py'. 
Be sure to follow the steps for building a engine file for segmentation mentioned in the [Readme File](https://github.com/yashreadytobox/JetsonYolov5/blob/main/README.md) 
Also @NishaniKasineshan if you get any issue while executing the file please let me know.
